### ISSUE TITLE
Update cachix cache?

### ISSUE THREAD

**Issue by chiroptical** [NorfairKing/intray#1]
https://github.com/NorfairKing/intray/blob/7f24257eaab3a2fa160183eb86f6e91358552a1f/flake.nix#L4-L5

Is it possible the cachix cache hasn't been updated in awhile? I am currently building `ghc-musl-9.6.5` on x86_64-linux which is somewhat surprising.

**Comment by NorfairKing** [comment]
Hey @chiroptical My cachix caches usually fill up very quickly and then things get evicted.
I'd need to get someone to sponsor some cachix subscription, or some charity from @domenkozar :P 
You're building ghc because you're building the statically linked version of intray (recommended), but you can also use the dynamically linked version and spend less time building things.

**Comment by chiroptical** [comment]
> but you can also use the dynamically linked version and spend less time building things.

How? I have this function,

```
    mkHomeManagerConfiguration = system: homeModule: let
      mkSystemModules = system:
        if system == "x86_64-linux"
        then [
          intray.homeManagerModules.${system}.default
        ]
        else [
        ];
```
in my `flake.nix` to enable intray for Linux systems. I don't understand how to override this thing. It might be nice to just provide both `static` and `default` similar to https://github.com/NorfairKing/intray/blob/757952f3cdeab2b81748560f69adac34b1919c46/flake.nix#L70-L73 I guess.

**Comment by NorfairKing** [comment]
@chiroptical ah right we could expose both as home manager modules. PR welcome
